"""System Architect Agent implementation."""

from __future__ import annotations

import uuid

from codeforge.agents.system_architect.api_designer import APIContractDesigner
from codeforge.agents.system_architect.data_model import DataModelDesigner
from codeforge.agents.system_architect.file_tree import FileTreeGenerator
from codeforge.agents.system_architect.risk_assessor import RiskAssessor
from codeforge.agents.system_architect.tech_stack import TechStackSelector
from codeforge.artifacts.prd import PRD
from codeforge.artifacts.tech_spec import TechSpec
from codeforge.core.agent_registry import BaseAgent
from codeforge.core.message_protocol import ArtifactType, Message, MessageType, create_artifact_submission


class SystemArchitectAgent(BaseAgent):
    """Turns PRD artifacts into implementation-ready technical specifications."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._stack_selector = TechStackSelector()
        self._data_model_designer = DataModelDesigner()
        self._api_designer = APIContractDesigner()
        self._file_tree_generator = FileTreeGenerator()
        self._risk_assessor = RiskAssessor()

    @property
    def role(self) -> str:
        return "system_architect"

    async def process_message(self, message: Message) -> None:
        if message.type != MessageType.TASK_ASSIGNMENT:
            return

        prd = self._load_prd(message)

        await self.update_status("Selecting technology stack", 0.2)
        tech_stack = self._stack_selector.select(prd)

        await self.update_status("Designing data model", 0.4)
        data_entities = self._data_model_designer.design(prd)

        await self.update_status("Designing API contracts", 0.6)
        api_endpoints = self._api_designer.design(prd, data_entities)

        await self.update_status("Generating file tree and risks", 0.8)
        file_tree = self._file_tree_generator.generate()
        risks = self._risk_assessor.assess(prd)

        spec = TechSpec(
            id=f"tech-spec-{uuid.uuid4().hex[:8]}",
            title=f"Technical Specification for {prd.title}",
            overview=f"Implementation plan for {prd.title}: {prd.summary}",
            tech_stack=tech_stack,
            data_entities=data_entities,
            api_endpoints=api_endpoints,
            file_tree=file_tree,
            risks=risks,
        )

        artifact_message = create_artifact_submission(
            artifact_id=spec.id,
            artifact_type=ArtifactType.TECH_SPEC,
            content=spec.to_dict(),
            sender=self.agent_id,
            validation_status="ready" if spec.is_ready_for_implementation() else "incomplete",
            notes="Generated by deterministic architecture pipeline; LLM prompt available for refinement.",
        )
        await self.send_message(artifact_message)
        await self.update_status("Tech spec submitted", 1.0)

    def _load_prd(self, message: Message) -> PRD:
        context = message.payload.get("context", {})
        if "prd" in context:
            return PRD.from_dict(context["prd"])

        specification = context.get("specification", message.payload.get("description", "Untitled app"))
        return PRD(
            id="prd-placeholder",
            title="Generated Application",
            summary=specification,
            goals=[specification],
        )
