"""Product Manager Agent implementation."""

from __future__ import annotations

from codeforge.agents.product_manager.clarification import ClarificationEngine
from codeforge.agents.product_manager.intent_parser import IntentParser
from codeforge.agents.product_manager.prd_generator import PRDGenerator
from codeforge.core.agent_registry import BaseAgent
from codeforge.core.message_protocol import (
    ArtifactType,
    Message,
    MessageType,
    create_artifact_submission,
)


class ProductManagerAgent(BaseAgent):
    """Turns natural language product requests into PRD artifacts."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._intent_parser = IntentParser()
        self._clarification_engine = ClarificationEngine()
        self._prd_generator = PRDGenerator()

    @property
    def role(self) -> str:
        return "product_manager"

    async def process_message(self, message: Message) -> None:
        if message.type != MessageType.TASK_ASSIGNMENT:
            return

        specification = message.payload.get("context", {}).get(
            "specification", message.payload.get("description", "")
        )

        await self.update_status("Parsing product intent", 0.2)
        intent = self._intent_parser.parse(specification)

        await self.update_status("Detecting ambiguities", 0.45)
        clarifications = self._clarification_engine.analyze(intent)

        await self.update_status("Generating PRD", 0.75)
        prd = self._prd_generator.generate(intent, clarifications)

        artifact_message = create_artifact_submission(
            artifact_id=prd.id,
            artifact_type=ArtifactType.PRD,
            content=prd.to_dict(),
            sender=self.agent_id,
            validation_status="ready" if prd.is_ready_for_architecture() else "needs_clarification",
            notes="Generated by deterministic PM pipeline; LLM prompt available for refinement.",
        )
        await self.send_message(artifact_message)
        await self.update_status("PRD submitted", 1.0)
