"""Product Manager Agent implementation."""

from __future__ import annotations

from codeforge.agents.llm_mixin import LLMMixin
from codeforge.agents.product_manager.clarification import ClarificationEngine
from codeforge.agents.product_manager.intent_parser import IntentParser
from codeforge.agents.product_manager.prd_generator import PRDGenerator
from codeforge.core.agent_registry import BaseAgent
from codeforge.core.llm_client import LlmClient
from codeforge.core.message_protocol import (
    ArtifactType,
    Message,
    MessageType,
    create_artifact_submission,
)
from codeforge.prompts.product_manager import (
    PRODUCT_MANAGER_SYSTEM_PROMPT,
    build_prd_prompt,
)


class ProductManagerAgent(LLMMixin, BaseAgent):
    """Turns natural language product requests into PRD artifacts."""

    def __init__(self, *args, llm_client: LlmClient | None = None, **kwargs):
        BaseAgent.__init__(self, *args, **kwargs)
        LLMMixin.__init__(self, llm_client=llm_client)
        self._intent_parser = IntentParser()
        self._clarification_engine = ClarificationEngine()
        self._prd_generator = PRDGenerator()

    @property
    def role(self) -> str:
        return "product_manager"

    async def process_message(self, message: Message) -> None:
        if message.type != MessageType.TASK_ASSIGNMENT:
            return

        specification = message.payload.get("context", {}).get(
            "specification", message.payload.get("description", "")
        )

        prd = None

        llm_available = await self._check_llm()
        if llm_available:
            await self.update_status("Reasoning with LLM", 0.15)
            context_digest = self.get_context_digest()

            response = await self.llm_reason(
                system_prompt=PRODUCT_MANAGER_SYSTEM_PROMPT,
                user_prompt=build_prd_prompt(specification, context_digest),
                temperature=0.3,
            )

            llm_data = self.parse_json_response(response)
            if llm_data:
                await self.update_status("Generating PRD from LLM output", 0.6)
                prd = self._prd_generator.generate_from_dict(llm_data, specification)
                await self.update_status("PRD finalized via LLM", 0.9)

        if prd is None:
            await self.update_status("Parsing product intent", 0.2)
            intent = self._intent_parser.parse(specification)

            await self.update_status("Detecting ambiguities", 0.45)
            clarifications = self._clarification_engine.analyze(intent)

            await self.update_status("Generating PRD (deterministic)", 0.75)
            prd = self._prd_generator.generate(intent, clarifications)

        scope_first = "core workflow"
        if prd.scope:
            in_scope = (
                prd.scope.in_scope
                if hasattr(prd.scope, "in_scope")
                else prd.scope.get("in_scope", ["core features"])
            )
            scope_first = in_scope[0] if in_scope else "core workflow"
        await self.discuss_with(
            "system_architect",
            f"I have completed the Product Requirements Document "
            f"for \u201c{prd.title}\u201d. "
            f"Key goals: {', '.join(prd.goals[:3])}. "
            f"Scope includes {scope_first}. "
            f"Edge cases and open questions have been catalogued. "
            f"Please design the architecture \u2014 I need a clean tech stack, "
            f"data model, and API contract.",
            reasoning=(
                "Parsed user intent from specification. "
                "Product scope is clearly defined for MVP delivery."
            ),
            plan_snippet=(
                f"Goals: {', '.join(prd.goals[:3])}. "
                f"Scope: {scope_first}."
            ),
        )

        artifact_message = create_artifact_submission(
            artifact_id=prd.id,
            artifact_type=ArtifactType.PRD,
            content=prd.to_dict(),
            sender=self.agent_id,
            validation_status=(
                "ready" if prd.is_ready_for_architecture() else "needs_clarification"
            ),
            notes=(
                "Generated via LLM reasoning"
                if llm_available
                else "Generated by deterministic PM pipeline"
            ),
        )
        await self.send_message(artifact_message)
        await self.update_status("PRD submitted", 1.0)
