"""Commit manager: creates and manages Git commits.

Every agent contribution becomes a real Git commit with proper
attribution, meaningful messages, and structured metadata.
"""

from __future__ import annotations

import os
from pathlib import Path
from datetime import UTC, datetime
from typing import Any

from codeforge.utils.logging import get_logger

logger = get_logger(__name__)


class CommitManager:
    def __init__(self, repo_path: str):
        self._repo_path = Path(repo_path)

    def commit(
        self,
        message: str,
        author_name: str = "CodeForge AI",
        author_email: str = "codeforge@ai.local",
        files: list[str] | None = None,
        phase: str = "",
        agent: str = "",
    ) -> dict[str, Any]:
        import git

        try:
            repo = git.Repo(self._repo_path)

            if files:
                for f in files:
                    file_path = self._repo_path / f
                    if file_path.exists():
                        repo.index.add([str(file_path)])
            else:
                repo.git.add(A=True)

            actor = git.Actor(author_name, author_email)
            full_message = self._format_message(message, phase, agent)

            commit = repo.index.commit(
                full_message,
                author=actor,
                committer=actor,
            )

            logger.info(
                f"Committed: {commit.hexsha[:8]} - {message[:60]}"
            )
            return {
                "sha": commit.hexsha,
                "short_sha": commit.hexsha[:8],
                "message": message,
                "author": author_name,
                "timestamp": datetime.now(UTC).isoformat(),
            }

        except Exception as e:
            logger.error(f"Commit failed: {e}")
            return {"error": str(e), "sha": ""}

    def get_commit_history(
        self, max_count: int = 20
    ) -> list[dict[str, Any]]:
        import git

        try:
            repo = git.Repo(self._repo_path)
            commits = []
            for c in repo.iter_commits(max_count=max_count):
                commits.append({
                    "sha": c.hexsha,
                    "short_sha": c.hexsha[:8],
                    "message": c.message.strip(),
                    "author": str(c.author),
                    "date": datetime.fromtimestamp(
                        c.committed_date, tz=UTC
                    ).isoformat(),
                })
            return commits
        except Exception:
            return []

    def get_file_history(
        self, file_path: str, max_count: int = 10
    ) -> list[dict[str, Any]]:
        import git

        try:
            repo = git.Repo(self._repo_path)
            commits = []
            for c in repo.iter_commits(paths=file_path, max_count=max_count):
                commits.append({
                    "sha": c.hexsha[:8],
                    "message": c.message.strip().split("\n")[0],
                    "author": str(c.author),
                })
            return commits
        except Exception:
            return []

    def _format_message(
        self, message: str, phase: str = "", agent: str = ""
    ) -> str:
        parts = [message]
        if phase and agent:
            parts.append(f"\nPhase: {phase} | Agent: {agent}")
        elif phase:
            parts.append(f"\nPhase: {phase}")
        elif agent:
            parts.append(f"\nAgent: {agent}")
        parts.append("\nGenerated by CodeForge AI")
        return "".join(parts)
